#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Semi AI Foundry, LLC
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
from __future__ import annotations

import hashlib
from pathlib import Path
import sys
import zipfile

EXPECTED_LEGAL_SUFFIXES = {
    "LICENSE",
    "NOTICE",
    "LICENSE_SCOPE.tsv",
    "LICENSES/CC-BY-NC-4.0.txt",
    "LICENSES/EPFL-MIT.txt",
    "LICENSES/PolyForm-Noncommercial-1.0.0.txt",
}


def wheel_in(directory: Path) -> Path:
    wheels = sorted(directory.glob("crg_research_validation-*.whl"))
    if len(wheels) != 1:
        raise SystemExit(f"expected one CRG wheel in {directory}, found {len(wheels)}")
    return wheels[0]


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def legal_suffix(name: str) -> str | None:
    marker = ".dist-info/licenses/"
    return name.split(marker, 1)[1] if marker in name else None


def inspect(path: Path) -> None:
    with zipfile.ZipFile(path) as archive:
        names = archive.namelist()
        if len(names) != len(set(names)):
            raise SystemExit("wheel contains duplicate paths")
        metadata_names = [name for name in names if name.endswith(".dist-info/METADATA")]
        if len(metadata_names) != 1:
            raise SystemExit("wheel must contain exactly one METADATA file")
        metadata = archive.read(metadata_names[0]).decode("utf-8")
        required = (
            "Version: 1.0.0",
            "Requires-Python: <3.14,>=3.12",
            "License-Expression: PolyForm-Noncommercial-1.0.0",
        )
        for line in required:
            if line not in metadata:
                raise SystemExit(f"wheel metadata missing: {line}")
        present = {suffix for name in names if (suffix := legal_suffix(name)) is not None}
        if present != EXPECTED_LEGAL_SUFFIXES:
            raise SystemExit(f"wheel legal payload mismatch: {sorted(present)}")
        if any(name.endswith((".pyc", ".pyo")) or "__pycache__" in name for name in names):
            raise SystemExit("wheel contains generated bytecode")


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit("usage: verify_wheel.py FIRST_BUILD_DIR SECOND_BUILD_DIR")
    first = wheel_in(Path(sys.argv[1]))
    second = wheel_in(Path(sys.argv[2]))
    inspect(first)
    inspect(second)
    first_digest = digest(first)
    second_digest = digest(second)
    if first_digest != second_digest:
        raise SystemExit(f"wheel builds differ: {first_digest} != {second_digest}")
    print(f"verified reproducible wheel sha256:{first_digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
